# see https://github.com/marketplace/actions/github-tag-bump
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  push:

env:
  BUILD: ${{ github.event.pull_request.merged == true && 'release' || 'snapshot' }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Debug output
        run: |
          echo "- GITHUB_REF: $GITHUB_REF" >> $GITHUB_STEP_SUMMARY
          echo "- GITHUB_SHA: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
          echo "- Merge Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- MERGE_COMMIT_SHA: $MERGE_COMMIT_SHA" >> $GITHUB_STEP_SUMMARY
          echo "- BUILD: $BUILD" >> $GITHUB_STEP_SUMMARY
        env:
          MERGE_COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ github.event.pull_request.merged == true }}
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          PRERELEASE: false
          DEFAULT_BUMP: patch
          # DEFAULT_BRANCH: master
          INITIAL_VERSION: 0.1.0
        id: bump

      # - uses: actions/checkout@v3

      - name: Create build artifacts
        run: |
          tar czvf out.tar.gz README.md

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.tar.gz"
      #     bodyFile: "README.md"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ github.event.pull_request.merged == true && steps.bump.outputs.new_tag || 'development' }}
          # title: 'Development Build'
          files: |
            bashrc
            *.tar.gz

