name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v3

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        tar czvf release.tgz README.md

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,*.md"
        bodyFile: "README.md"
